name: The Quality Gate System


on:
  pull_request:
    branches:
      - main

jobs:
  lint-code:
    run-on: ubuntu-latest
    steps:
      - name: Download the code
        uses: actions/checkout@v4

      - name: Install shellchecker
        run: sudo apt-get install -y shellcheck

      - name: Check the code
        run: shellcheck ./deploy.sh
