name: My First Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'hello.sh'

jobs:
  run-my-script:
    runs-on: ubuntu-latest
    steps:
      - name: Download the code
        uses: actions/checkout@v4

      - name: Execute the Bash Script
        run: ./hello.sh
