name: Matrix Test

on:
  workflow_dispatch:


jobs:
  test-the-code:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18, 20, 22]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Print the OS
        run: |
           echo "Hello , i'm runnin on ${{ matrix.os }} with Node version : ${{ matrix.node-version }}"
