name: Secure Login

on:
  push:
    paths:
      - 'login.sh'

jobs:
  secure-login:
    runs-on: ubuntu-latest
    steps:
      - name: Download the code
        uses: actions/checkout@v4

      - name: Run secure login script
        env:
          API_TOKEN: ${{ secrets.SUPER_SECRET_TOKEN }}
        run: ./login.sh
